config/routes.rb
Customers::Application.routes.draw do
  resources :customers do
    resources :projects
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :email, :birthday

  validates_presence_of :last_name, :email
  validates_uniqueness_of :email
  validates_length_of :first_name, :last_name, :within => 3..50, :allow_blank => true
  validates_format_of :email, :with => /^.+@.+\..+$/, :message => "doesn't look like an email address"

  validate do
    if email =~ /aol\.com$/
      errors.add(:email, "we don't want customers from AOL")
    end
  end

  has_many :notes
  has_many :projects

  scope :adult, lambda { where(["birthday < ?", 18.years.ago]) }
  scope :from, lambda { |city| where(:city => city) }

  def reached_project_limit?
    projects.count >= 10
  end

  # class << self
  #   def adult
  #     where(["birthday < ?", 18.years.ago])
  #   end

  #   def from(city)
  #     where(:city => city)
  #   end
  # end

  after_create :create_initial_note
  after_update :create_update_note

  def create_initial_note
    notes.create(:text => "Customer has been created.")
  end

  def create_update_note
    notes.create(:text => "Customer has been updated. Changed attributes are:\n\n#{changed_attributes}")
  end

  def full_name
    # last_name + ", " + first_name
    # [last_name, ", ", first_name].join
    # [last_name, first_name].join(", ")
    "#{last_name}, #{first_name}"
  end

  def to_s
    full_name
  end

  def to_param
    "#{id}-#{first_name.parameterize}"
  end

  # attr_accessor :email_confirmation

  # validate :check_email_confirmation

  # def check_email_confirmation
  #   if email != email_confirmation
  #     errors.add(:email_confirmation, "doesn't match your email address")
  #   end
  # end

  # def email_confirmation
  #   @email_confirmation
  # end

  # def email_confirmation=(value)
  #   @email_confirmation = value
  # end
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :customer_id, :text
  belongs_to :customer
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :title, :customer_id
  validates_presence_of :customer_id, :title

  belongs_to :customer

  validate do
    if customer.reached_project_limit?
      errors.add(:customer, "has reached project limit")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :force_login

  def force_login
    # ...
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_filter :load_customer, :only => [:show, :edit, :update, :destroy]
  skip_before_filter :force_login, :only => [:show]
  respond_to :html, :xml, :json

  def load_customer
    @customer = Customer.find(params[:id])
  end

  def index
    @customers = Customer.all
    respond_with(@customers)
  end

  def show
    respond_with(@customer, :include => { :projects => { :except => :customer_id }},
      :except => :email)
  end

  def destroy
    @customer.destroy
    redirect_to customers_path
  end

  def new
    @customer = Customer.new
    respond_with @customer
  end

  def create
    @customer = Customer.new(params[:customer])

    if @customer.save
      respond_with(@customer) do |format|
        format.html { redirect_to customers_path }
      end
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @customer.update_attributes(params[:customer])
      respond_with @customer
    else
      render :action => 'edit'
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
  belongs_to :customer

  def update
    update! do |f|
      f.html { redirect_to [@project.customer, :projects] }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
  def foo
    'bar'
  end

  def customer_photo(customer)
    image_tag('http://placekitten.com/100/80')
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for @customer do |f| %>
  <%= f.input :first_name, :placeholder => "Please enter your first name", :hint => "You better use your real first name!" %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :birthday,
        :start_year => Time.now.year,
        :end_year => Time.now.year - 100,
        :include_blank => true %>
  <%= f.submit %>
<% end %>

app/views/customers/edit.html.erb
<h1>Edit customer</h1>

<%= render 'form' %>

app/views/customers/index.html.erb
<h1>List of all customers</h1>

<p><%= link_to "Add customer", new_customer_path %></p>

<table>
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.full_name %></td>
      <td><%= customer.email %></td>
      <td><%= customer.birthday %></td>
      <td>
        <%= link_to 'Show', customer %>
        <%= link_to 'Projects', [customer, :projects] %>

        <%= link_to 'Edit', [:edit, customer] %>
        <%= link_to 'Delete', customer, :method => :delete,
              :confirm => "Are you sure?" %>
      </td>
    </tr>
  <% end %>
</table>

app/views/customers/index.pdf.erb
yay!

app/views/customers/new.html.erb
<h1>Add a new customer</h1>

<%= render 'form' %>

app/views/customers/show.html.erb
<p>
  <%= customer_photo @customer %>
</p>

<p>First name: <%= @customer.first_name %></p>
<p>Last name: <%= @customer.last_name %></p>
<p>Email: <%= @customer.email %></p>
<p>Birthday: <%= @customer.birthday %></p>

<h3>Notes</h3>

<%= render @customer.notes %>


<%= link_to 'Edit', edit_customer_path %>
<%= link_to 'All customers', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Customers</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_note.html.erb
<h3><%= note.created_at %></h3>
<p>
  <%= note.text %>
</p>

app/views/projects/_form.html.erb
<%= simple_form_for [@project.customer, @project] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.association :customer %>

  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Projects owned by <%= @customer %></h1>

<table>
  <% @projects.each do |project| %>
    <tr>
      <td><%= project.title %></td>
      <td>
        <%= link_to 'Show', [project.customer, project] %>
        <%= link_to 'Edit', [:edit, project.customer, project] %>
      </td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to "Add New Project", new_customer_project_path %>
  <%= link_to "Return to customer", @customer %>
</p>

app/views/projects/new.html.erb
<h1>New Project</h1>

<% if @customer.reached_project_limit? %>
  <p><strong>This customer has reached the project limit. Beware!</strong></p>
<% end %>

<%= render 'form' %>

app/views/projects/show.html.erb
<h1>Project: <%= @project.title %></h1>

<p>
  <%= @project.description %>
</p>

<p>
  This project belongs to <%= @customer %>.
</p>

<%= link_to 'All Projects', customer_projects_path %>